# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MMS support in SMS client
email: anikketkumar786@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about improving MMS support to the KDE-Connect's SMS app
  as part of GSoC project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: anikket7
github_username:  anikket786

# Build settings
markdown: kramdown
